### ISSUE TITLE
minSdkVersion 21

### ISSUE THREAD

**Issue by eried** [pablojimenezmateo/GodotAndroidBluetoothDemo#1]
```
\GodotAndroidBluetoothDemo-master\android\build\src\debug\AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [GodotBluetooth344-debug.aar] 
```

Hi! I am very beginner in all this godot and android, I am trying to get this example running but I get that error. I am doing something wrong? could you update this to at least version 21?

PS: Ultimately I want to run a game in a Meta Quest 2 with BLE capabilities 

Thanks!

**Comment by pablojimenezmateo** [comment]
Hi eried,

this happens because you are targeting an old Android SDK (version 19) and my plugin needs at least 21.

On the export options for Android make sure you select Min sdk 21 (or greater):

![image](https://user-images.githubusercontent.com/2511009/194752957-90cf8173-aba8-4463-90bd-ef9db5192cd1.png)

Let me know if that fixes your issue :)

**Comment by eried** [comment]
ohh! sorry! so stupid! now it compiles :) scans but does not connect (says `[DEBUG] 62`), but I guess that is another matter I need to do more testing
